name: Create Backup

on:
  workflow_dispatch

jobs:
  create-backup:
    runs-on: ubuntu-latest
    name: Create Backup
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - name: create output directory
        run: mkdir output
      - name: Run PG Dump
        uses: addnab/docker-run-action@v2
        env:
          POSTGRES_PASSWORD: ${{ secrets.NEON_POSTGRES_CONNECTSTR }}
        with:
          image: postgres:latest
          options: -v ${{ github.workspace }}/output:/output
          run: |
            echo "Creating backup"
            pg_dump ${{ secrets.NEON_POSTGRES_CONNECTSTR }} > output/backup.sql
            echo "Backup created"
            ls -la output
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Upload Backup
        id: upload-backup
        uses: actions/upload-artifact@v4
        with:
          path: output
          name: backup-${{ steps.date.outputs.date }}-${{ github.run_id }}
